### ISSUE TITLE
ATF 479 remaining parsing issues

### ISSUE THREAD

**Issue by cmc333333** [18F/regulations-parser#56]
* [x] Creating collapsed markers when we probably shouldn't. See section 11, definition "destructive device" and "firearm" as well as section 141 (#68)
* [x] Missing paragraphs 21(b), 26(a)(3), 34(e) likely due to AMDPAR errors (#58, #59, 18F/fr-notices#1, 18F/fr-notices#2, 18F/fr-notices#3)
* [x] Missing unmarked paragraph after section 11. This is an `EXTRACT`, which should probably look like an appendix note (#69)
* [x] Missing unmarked paragraph after 111(a)(3). This is a `FP` (#57)
* [x] Need to account for word changes, etc. as seen in Final Rules (#58, #59, 18F/fr-notices#1, 18F/fr-notices#2, 18F/fr-notices#3)
* [x] Most the the definitions in section 11 are not being picked up. I know CFPB's done some work here -- we'll want to pull that in (#64), though we're missing one (#65)
* [x] Subject groupings are being lost (#66, 18F/regulations-site#13, 18F/regulations-site#15)

**Comment by cmc333333** [comment]
Note the missing marker paragraphs are due to misparsing instructions in https://www.federalregister.gov/articles/2014/08/11/2014-18842/technical-amendments-to-regulations
